#app.id=app-carson-weixin
#apollo.meta=http://192.168.90.131:8080

#server.port=8200
#spring.application.name=app-carson-weixin
#eureka.client.service-url.defaultZone=http://localhost:8100/eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
server:
  port: 8200
spring:
  application:
    name: app-carson-weixin
  redis:
    host: 12.0.0.1
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1

logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    configs:
      - appId: wx99ae2e3410052533
        secret: e54d109067ba9735d2ac4b88ee83b0a3
        token: carson

mayikt:
  weixin:
    registration:
      code:
        ###微信注册码消息
        message:  您的注册码为:%s，请关注<a href="https://ke.qq.com/course/273548">腾讯课堂免费公开课</a>，欢迎观看97后架构师余老师的精品课程讲解。官方QQ群：<a href='https://jq.qq.com/?_wv=1027&k=5TVfAMF'>193086273</a>，期待你的加入，感谢！
    ###默认提示消息
    default:
      registration:
        code:
          message: 您的消息，我们已经收到,会及时回复给您的!